/*******************************************************************************
 * Copyright (c) 2011, 2014 Profactor GmbH
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Gerhard Ebenhofer, Matthias Plasch
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!


#include "forteinit.h"

#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_any.h>

#include <C:/FORTE_dev/forte-sourcecode/external_modules/VDMA/forte_spinner.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_any_bit.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_any_elementary.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_any_int.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_any_magnitude.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_any_num.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_any_real.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_any_string.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_array.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_bool.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_byte.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_date.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_date_and_time.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_dint.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_dword.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_int.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_lint.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_lreal.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_lword.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_real.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_sint.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_string.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_time.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_time_of_day.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_udint.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_uint.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_ulint.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_usint.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_word.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/core/datatypes/forte_wstring.h>


#include <C:/FORTE_dev/forte-sourcecode/external_modules/VDMA/Bunker.h>
#include <C:/FORTE_dev/forte-sourcecode/external_modules/VDMA/Camera.h>
#include <C:/FORTE_dev/forte-sourcecode/external_modules/VDMA/ContentFilter.h>
#include <C:/FORTE_dev/forte-sourcecode/external_modules/VDMA/FB_Detect_VarChange.h>
#include <C:/FORTE_dev/forte-sourcecode/external_modules/VDMA/Vibrator.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Arithmetic/F_ADD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Arithmetic/F_ADD_DT_TIME.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Arithmetic/F_ADD_TOD_TIME.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Arithmetic/F_DIV.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Arithmetic/F_DIVTIME.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Arithmetic/F_EXPT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Arithmetic/F_MOD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Arithmetic/F_MOVE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Arithmetic/F_MUL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Arithmetic/F_MULTIME.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Arithmetic/F_SUB.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Arithmetic/F_SUB_DATE_DATE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Arithmetic/F_SUB_DT_DT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Arithmetic/F_SUB_DT_TIME.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Arithmetic/F_SUB_TOD_TIME.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Arithmetic/F_SUB_TOD_TOD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Arithmetic/F_TRUNC.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Arithmetic/GEN_ADD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/BistableElements/FB_RS.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/BistableElements/FB_SR.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/BitwiseOperators/F_AND.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/BitwiseOperators/F_NOT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/BitwiseOperators/F_OR.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/BitwiseOperators/F_ROL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/BitwiseOperators/F_ROR.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/BitwiseOperators/F_SHL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/BitwiseOperators/F_SHR.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/BitwiseOperators/F_XOR.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/BitwiseOperators/GEN_AND.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/BitwiseOperators/GEN_OR.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/BitwiseOperators/GEN_XOR.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/CharacterString/F_CONCAT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/CharacterString/F_CONCAT_DATE_TOD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/CharacterString/F_DELETE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/CharacterString/F_FIND.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/CharacterString/F_INSERT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/CharacterString/F_LEFT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/CharacterString/F_LEN.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/CharacterString/F_MID.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/CharacterString/F_REPLACE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/CharacterString/F_RIGHT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Comparison/F_EQ.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Comparison/F_GE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Comparison/F_GT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Comparison/F_LE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Comparison/F_LT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Comparison/F_NE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BCD/F_BYTE_BCD_TO_USINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BCD/F_DWORD_BCD_TO_UDINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BCD/F_LWORD_BCD_TO_ULINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BCD/F_UDINT_TO_BCD_DWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BCD/F_UINT_TO_BCD_WORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BCD/F_ULINT_TO_BCD_LWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BCD/F_USINT_TO_BCD_BYTE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BCD/F_WORD_BCD_TO_UINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BOOL/F_BOOL_TO_BYTE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BOOL/F_BOOL_TO_DINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BOOL/F_BOOL_TO_DWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BOOL/F_BOOL_TO_INT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BOOL/F_BOOL_TO_LINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BOOL/F_BOOL_TO_LWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BOOL/F_BOOL_TO_SINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BOOL/F_BOOL_TO_STRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BOOL/F_BOOL_TO_UDINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BOOL/F_BOOL_TO_UINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BOOL/F_BOOL_TO_ULINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BOOL/F_BOOL_TO_USINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BOOL/F_BOOL_TO_WORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BOOL/F_BOOL_TO_WSTRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BYTE/F_BYTE_TO_DINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BYTE/F_BYTE_TO_DWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BYTE/F_BYTE_TO_INT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BYTE/F_BYTE_TO_LINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BYTE/F_BYTE_TO_LWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BYTE/F_BYTE_TO_SINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BYTE/F_BYTE_TO_STRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BYTE/F_BYTE_TO_UDINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BYTE/F_BYTE_TO_UINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BYTE/F_BYTE_TO_ULINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BYTE/F_BYTE_TO_USINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BYTE/F_BYTE_TO_WORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/BYTE/F_BYTE_TO_WSTRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DINT/F_DINT_TO_BYTE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DINT/F_DINT_TO_DWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DINT/F_DINT_TO_INT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DINT/F_DINT_TO_LINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DINT/F_DINT_TO_LREAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DINT/F_DINT_TO_LWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DINT/F_DINT_TO_REAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DINT/F_DINT_TO_SINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DINT/F_DINT_TO_STRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DINT/F_DINT_TO_UDINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DINT/F_DINT_TO_UINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DINT/F_DINT_TO_ULINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DINT/F_DINT_TO_USINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DINT/F_DINT_TO_WORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DINT/F_DINT_TO_WSTRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DT/F_DT_TO_DATE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DT/F_DT_TO_TOD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DWORD/F_DWORD_TO_BYTE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DWORD/F_DWORD_TO_DINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DWORD/F_DWORD_TO_INT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DWORD/F_DWORD_TO_LINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DWORD/F_DWORD_TO_LWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DWORD/F_DWORD_TO_REAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DWORD/F_DWORD_TO_SINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DWORD/F_DWORD_TO_STRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DWORD/F_DWORD_TO_UDINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DWORD/F_DWORD_TO_UINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DWORD/F_DWORD_TO_ULINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DWORD/F_DWORD_TO_USINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DWORD/F_DWORD_TO_WORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/DWORD/F_DWORD_TO_WSTRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/INT/F_INT_TO_BYTE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/INT/F_INT_TO_DINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/INT/F_INT_TO_DWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/INT/F_INT_TO_LINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/INT/F_INT_TO_LREAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/INT/F_INT_TO_LWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/INT/F_INT_TO_REAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/INT/F_INT_TO_SINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/INT/F_INT_TO_STRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/INT/F_INT_TO_UDINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/INT/F_INT_TO_UINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/INT/F_INT_TO_ULINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/INT/F_INT_TO_USINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/INT/F_INT_TO_WORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/INT/F_INT_TO_WSTRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LINT/F_LINT_TO_BYTE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LINT/F_LINT_TO_DINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LINT/F_LINT_TO_DWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LINT/F_LINT_TO_INT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LINT/F_LINT_TO_LREAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LINT/F_LINT_TO_LWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LINT/F_LINT_TO_REAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LINT/F_LINT_TO_SINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LINT/F_LINT_TO_STRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LINT/F_LINT_TO_UDINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LINT/F_LINT_TO_UINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LINT/F_LINT_TO_ULINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LINT/F_LINT_TO_USINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LINT/F_LINT_TO_WORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LINT/F_LINT_TO_WSTRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LREAL/F_LREAL_TO_DINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LREAL/F_LREAL_TO_INT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LREAL/F_LREAL_TO_LINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LREAL/F_LREAL_TO_LWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LREAL/F_LREAL_TO_REAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LREAL/F_LREAL_TO_SINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LREAL/F_LREAL_TO_STRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LREAL/F_LREAL_TO_UDINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LREAL/F_LREAL_TO_UINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LREAL/F_LREAL_TO_ULINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LREAL/F_LREAL_TO_USINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LREAL/F_LREAL_TO_WSTRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LWORD/F_LWORD_TO_BYTE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LWORD/F_LWORD_TO_DINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LWORD/F_LWORD_TO_DWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LWORD/F_LWORD_TO_INT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LWORD/F_LWORD_TO_LINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LWORD/F_LWORD_TO_LREAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LWORD/F_LWORD_TO_SINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LWORD/F_LWORD_TO_STRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LWORD/F_LWORD_TO_UDINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LWORD/F_LWORD_TO_UINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LWORD/F_LWORD_TO_ULINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LWORD/F_LWORD_TO_USINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LWORD/F_LWORD_TO_WORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/LWORD/F_LWORD_TO_WSTRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/REAL/F_REAL_TO_DINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/REAL/F_REAL_TO_DWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/REAL/F_REAL_TO_INT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/REAL/F_REAL_TO_LINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/REAL/F_REAL_TO_LREAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/REAL/F_REAL_TO_SINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/REAL/F_REAL_TO_STRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/REAL/F_REAL_TO_UDINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/REAL/F_REAL_TO_UINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/REAL/F_REAL_TO_ULINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/REAL/F_REAL_TO_USINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/REAL/F_REAL_TO_WSTRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/SINT/F_SINT_TO_BYTE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/SINT/F_SINT_TO_DINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/SINT/F_SINT_TO_DWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/SINT/F_SINT_TO_INT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/SINT/F_SINT_TO_LINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/SINT/F_SINT_TO_LREAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/SINT/F_SINT_TO_LWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/SINT/F_SINT_TO_REAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/SINT/F_SINT_TO_STRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/SINT/F_SINT_TO_UDINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/SINT/F_SINT_TO_UINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/SINT/F_SINT_TO_ULINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/SINT/F_SINT_TO_USINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/SINT/F_SINT_TO_WORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/SINT/F_SINT_TO_WSTRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/STRING/F_STRING_TO_BOOL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/STRING/F_STRING_TO_BYTE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/STRING/F_STRING_TO_DINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/STRING/F_STRING_TO_DWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/STRING/F_STRING_TO_INT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/STRING/F_STRING_TO_LINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/STRING/F_STRING_TO_LREAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/STRING/F_STRING_TO_LWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/STRING/F_STRING_TO_REAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/STRING/F_STRING_TO_SINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/STRING/F_STRING_TO_TIME.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/STRING/F_STRING_TO_UDINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/STRING/F_STRING_TO_UINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/STRING/F_STRING_TO_ULINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/STRING/F_STRING_TO_USINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/STRING/F_STRING_TO_WORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/STRING/F_STRING_TO_WSTRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/TIME/F_TIME_IN_MS_TO_LINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/TIME/F_TIME_IN_MS_TO_LREAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/TIME/F_TIME_IN_MS_TO_ULINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/TIME/F_TIME_IN_NS_TO_LINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/TIME/F_TIME_IN_NS_TO_LREAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/TIME/F_TIME_IN_NS_TO_ULINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/TIME/F_TIME_IN_S_TO_LINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/TIME/F_TIME_IN_S_TO_LREAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/TIME/F_TIME_IN_S_TO_ULINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/TIME/F_TIME_IN_US_TO_LINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/TIME/F_TIME_IN_US_TO_LREAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/TIME/F_TIME_IN_US_TO_ULINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/TIME/F_TIME_TO_STRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/TIME/F_TIME_TO_WSTRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UDINT/F_UDINT_TO_BYTE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UDINT/F_UDINT_TO_DINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UDINT/F_UDINT_TO_DWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UDINT/F_UDINT_TO_INT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UDINT/F_UDINT_TO_LINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UDINT/F_UDINT_TO_LREAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UDINT/F_UDINT_TO_LWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UDINT/F_UDINT_TO_REAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UDINT/F_UDINT_TO_SINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UDINT/F_UDINT_TO_STRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UDINT/F_UDINT_TO_UINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UDINT/F_UDINT_TO_ULINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UDINT/F_UDINT_TO_WORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UDINT/F_UDINT_TO_WSTRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UINT/F_UINT_TO_BYTE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UINT/F_UINT_TO_DINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UINT/F_UINT_TO_DWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UINT/F_UINT_TO_INT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UINT/F_UINT_TO_LINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UINT/F_UINT_TO_LREAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UINT/F_UINT_TO_LWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UINT/F_UINT_TO_REAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UINT/F_UINT_TO_SINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UINT/F_UINT_TO_STRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UINT/F_UINT_TO_UDINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UINT/F_UINT_TO_ULINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UINT/F_UINT_TO_USINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UINT/F_UINT_TO_WORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/UINT/F_UINT_TO_WSTRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/ULINT/F_ULINT_TO_BYTE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/ULINT/F_ULINT_TO_DINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/ULINT/F_ULINT_TO_DWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/ULINT/F_ULINT_TO_INT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/ULINT/F_ULINT_TO_LINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/ULINT/F_ULINT_TO_LREAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/ULINT/F_ULINT_TO_LWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/ULINT/F_ULINT_TO_REAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/ULINT/F_ULINT_TO_SINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/ULINT/F_ULINT_TO_STRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/ULINT/F_ULINT_TO_UDINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/ULINT/F_ULINT_TO_UINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/ULINT/F_ULINT_TO_USINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/ULINT/F_ULINT_TO_WORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/ULINT/F_ULINT_TO_WSTRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/USINT/F_USINT_TO_BYTE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/USINT/F_USINT_TO_DINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/USINT/F_USINT_TO_DWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/USINT/F_USINT_TO_INT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/USINT/F_USINT_TO_LINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/USINT/F_USINT_TO_LREAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/USINT/F_USINT_TO_LWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/USINT/F_USINT_TO_REAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/USINT/F_USINT_TO_SINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/USINT/F_USINT_TO_STRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/USINT/F_USINT_TO_UDINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/USINT/F_USINT_TO_UINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/USINT/F_USINT_TO_ULINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/USINT/F_USINT_TO_WORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/USINT/F_USINT_TO_WSTRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WORD/F_WORD_TO_BYTE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WORD/F_WORD_TO_DINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WORD/F_WORD_TO_DWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WORD/F_WORD_TO_INT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WORD/F_WORD_TO_LINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WORD/F_WORD_TO_LWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WORD/F_WORD_TO_SINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WORD/F_WORD_TO_STRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WORD/F_WORD_TO_UDINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WORD/F_WORD_TO_UINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WORD/F_WORD_TO_ULINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WORD/F_WORD_TO_USINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WORD/F_WORD_TO_WSTRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WSTRING/F_WSTRING_TO_BOOL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WSTRING/F_WSTRING_TO_BYTE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WSTRING/F_WSTRING_TO_DINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WSTRING/F_WSTRING_TO_DWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WSTRING/F_WSTRING_TO_INT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WSTRING/F_WSTRING_TO_LINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WSTRING/F_WSTRING_TO_LREAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WSTRING/F_WSTRING_TO_LWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WSTRING/F_WSTRING_TO_REAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WSTRING/F_WSTRING_TO_SINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WSTRING/F_WSTRING_TO_STRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WSTRING/F_WSTRING_TO_TIME.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WSTRING/F_WSTRING_TO_UDINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WSTRING/F_WSTRING_TO_UINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WSTRING/F_WSTRING_TO_ULINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WSTRING/F_WSTRING_TO_USINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Conversion/WSTRING/F_WSTRING_TO_WORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Counters/FB_CTD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Counters/FB_CTD_DINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Counters/FB_CTD_LINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Counters/FB_CTD_UDINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Counters/FB_CTD_ULINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Counters/FB_CTU.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Counters/FB_CTUD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Counters/FB_CTUD_DINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Counters/FB_CTUD_LINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Counters/FB_CTUD_ULINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Counters/FB_CTU_DINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Counters/FB_CTU_LINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Counters/FB_CTU_UDINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Counters/FB_CTU_ULINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/EdgeDetection/FB_F_TRIG.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/EdgeDetection/FB_R_TRIG.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Numerical/F_ABS.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Numerical/F_ACOS.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Numerical/F_ASIN.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Numerical/F_ATAN.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Numerical/F_COS.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Numerical/F_EXP.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Numerical/F_LN.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Numerical/F_LOG.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Numerical/F_SIN.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Numerical/F_SQRT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Numerical/F_TAN.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Selection/F_LIMIT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Selection/F_MAX.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Selection/F_MIN.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Selection/F_MUX_2.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Selection/F_SEL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Timers/FB_TOF.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Timers/FB_TON.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/IEC61131-3/Timers/FB_TP.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/convert/BOOL2BOOL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/convert/BYTE2BYTE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/convert/DINT2DINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/convert/DWORD2DWORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/convert/GEN_STRUCT_DEMUX.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/convert/GEN_STRUCT_MUX.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/convert/INT2INT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/convert/LREAL2LREAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/convert/REAL2REAL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/convert/SINT2SINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/convert/STRING2STRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/convert/TIME2TIME.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/convert/UDINT2UDINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/convert/UINT2UINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/convert/USINT2USINT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/convert/WORD2WORD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/convert/WSTRING2WSTRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/reconfiguration/EC_KILL_ELEM.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/reconfiguration/EC_SET_EVT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/reconfiguration/EC_START_ELEM.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/reconfiguration/EC_STOP_ELEM.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/reconfiguration/ST_CREATE_CONN.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/reconfiguration/ST_CREATE_FB.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/reconfiguration/ST_DEL_CONN.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/reconfiguration/ST_DEL_FB.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/reconfiguration/ST_REC_CONN.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/reconfiguration/ST_SET_PARM.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/utils/E_STOPWATCH.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/utils/FB_RANDOM.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/utils/GEN_APPEND_STRING.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/utils/GEN_ARRAY2ARRAY.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/utils/GEN_ARRAY2VALUES.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/utils/GEN_CSV_WRITER.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/utils/GEN_F_MUX.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/utils/GEN_VALUES2ARRAY.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/utils/GET_AT_INDEX.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/utils/GET_STRUCT_VALUE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/utils/OUT_ANY_CONSOLE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/utils/SET_AT_INDEX.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/utils/STEST_END.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/modules/utils/TEST_CONDITION.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/events/ARTimeOut.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/events/ATimeOut.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/events/E_CTD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/events/E_CTU.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/events/E_CTUD.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/events/E_CYCLE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/events/E_DELAY.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/events/E_DEMUX.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/events/E_D_FF.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/events/E_F_TRIG.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/events/E_MERGE.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/events/E_PERMIT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/events/E_RDELAY.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/events/E_REND.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/events/E_RESTART.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/events/E_RS.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/events/E_RTimeOut.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/events/E_R_TRIG.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/events/E_SELECT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/events/E_SPLIT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/events/E_SR.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/events/E_SWITCH.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/events/E_TRAIN.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/events/E_T_FF.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/events/E_TimeOut.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/events/GEN_E_DEMUX.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/events/GEN_E_MUX.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/ita/DEV_MGR.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/ita/EMB_RES.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/ita/RMT_RES.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/net/GEN_CLIENT.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/net/GEN_PUBL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/net/GEN_PUBLISH.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/net/GEN_SERVER.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/net/GEN_SUBL.h>
#include <C:/FORTE_dev/forte-sourcecode/org.eclipse.4diac.forte/src/stdfblib/net/GEN_SUBSCRIBE.h>


extern "C"
void initForte()
{
  CIEC_ANY::dummyInit();
    CIEC_ANY_BIT::dummyInit();
  CIEC_ANY_ELEMENTARY::dummyInit();
  CIEC_ANY_INT::dummyInit();
  CIEC_ANY_MAGNITUDE::dummyInit();
  CIEC_ANY_NUM::dummyInit();
  CIEC_ANY_REAL::dummyInit();
  CIEC_ANY_STRING::dummyInit();
  CIEC_ARRAY::dummyInit();
  CIEC_BOOL::dummyInit();
  CIEC_BYTE::dummyInit();
  CIEC_DATE::dummyInit();
  CIEC_DATE_AND_TIME::dummyInit();
  CIEC_DINT::dummyInit();
  CIEC_DWORD::dummyInit();
  CIEC_INT::dummyInit();
  CIEC_LINT::dummyInit();
  CIEC_LREAL::dummyInit();
  CIEC_LWORD::dummyInit();
  CIEC_REAL::dummyInit();
  CIEC_SINT::dummyInit();
  CIEC_STRING::dummyInit();
  CIEC_TIME::dummyInit();
  CIEC_TIME_OF_DAY::dummyInit();
  CIEC_UDINT::dummyInit();
  CIEC_UINT::dummyInit();
  CIEC_ULINT::dummyInit();
  CIEC_USINT::dummyInit();
  CIEC_WORD::dummyInit();
  CIEC_WSTRING::dummyInit();
  CIEC_spinner::dummyInit();


    BOOL2BOOL::dummyInit();
  BYTE2BYTE::dummyInit();
  DEV_MGR::dummyInit();
  DINT2DINT::dummyInit();
  DWORD2DWORD::dummyInit();
  EMB_RES::dummyInit();
  E_CTU::dummyInit();
  E_CYCLE::dummyInit();
  E_DELAY::dummyInit();
  E_DEMUX::dummyInit();
  E_D_FF::dummyInit();
  E_F_TRIG::dummyInit();
  E_MERGE::dummyInit();
  E_PERMIT::dummyInit();
  E_RDELAY::dummyInit();
  E_REND::dummyInit();
  E_RESTART::dummyInit();
  E_RS::dummyInit();
  E_R_TRIG::dummyInit();
  E_SELECT::dummyInit();
  E_SPLIT::dummyInit();
  E_SR::dummyInit();
  E_SWITCH::dummyInit();
  FB_CTD::dummyInit();
  FB_CTD_DINT::dummyInit();
  FB_CTD_LINT::dummyInit();
  FB_CTD_UDINT::dummyInit();
  FB_CTD_ULINT::dummyInit();
  FB_CTU::dummyInit();
  FB_CTUD::dummyInit();
  FB_CTUD_DINT::dummyInit();
  FB_CTUD_LINT::dummyInit();
  FB_CTUD_ULINT::dummyInit();
  FB_CTU_DINT::dummyInit();
  FB_CTU_LINT::dummyInit();
  FB_CTU_UDINT::dummyInit();
  FB_CTU_ULINT::dummyInit();
  FB_F_TRIG::dummyInit();
  FB_RS::dummyInit();
  FB_R_TRIG::dummyInit();
  FB_SR::dummyInit();
  FB_TOF::dummyInit();
  FB_TON::dummyInit();
  FB_TP::dummyInit();
  FORTE_ARTimeOut::dummyInit();
  FORTE_ATimeOut::dummyInit();
  FORTE_Bunker::dummyInit();
  FORTE_Camera::dummyInit();
  FORTE_ContentFilter::dummyInit();
  FORTE_EC_KILL_ELEM::dummyInit();
  FORTE_EC_SET_EVT::dummyInit();
  FORTE_EC_START_ELEM::dummyInit();
  FORTE_EC_STOP_ELEM::dummyInit();
  FORTE_E_CTD::dummyInit();
  FORTE_E_CTUD::dummyInit();
  FORTE_E_RTimeOut::dummyInit();
  FORTE_E_STOPWATCH::dummyInit();
  FORTE_E_TRAIN::dummyInit();
  FORTE_E_T_FF::dummyInit();
  FORTE_E_TimeOut::dummyInit();
  FORTE_FB_Detect_VarChange::dummyInit();
  FORTE_FB_RANDOM::dummyInit();
  FORTE_F_ABS::dummyInit();
  FORTE_F_ACOS::dummyInit();
  FORTE_F_ADD::dummyInit();
  FORTE_F_ADD_DT_TIME::dummyInit();
  FORTE_F_ADD_TOD_TIME::dummyInit();
  FORTE_F_AND::dummyInit();
  FORTE_F_ASIN::dummyInit();
  FORTE_F_ATAN::dummyInit();
  FORTE_F_BOOL_TO_BYTE::dummyInit();
  FORTE_F_BOOL_TO_DINT::dummyInit();
  FORTE_F_BOOL_TO_DWORD::dummyInit();
  FORTE_F_BOOL_TO_INT::dummyInit();
  FORTE_F_BOOL_TO_LINT::dummyInit();
  FORTE_F_BOOL_TO_LWORD::dummyInit();
  FORTE_F_BOOL_TO_SINT::dummyInit();
  FORTE_F_BOOL_TO_STRING::dummyInit();
  FORTE_F_BOOL_TO_UDINT::dummyInit();
  FORTE_F_BOOL_TO_UINT::dummyInit();
  FORTE_F_BOOL_TO_ULINT::dummyInit();
  FORTE_F_BOOL_TO_USINT::dummyInit();
  FORTE_F_BOOL_TO_WORD::dummyInit();
  FORTE_F_BOOL_TO_WSTRING::dummyInit();
  FORTE_F_BYTE_BCD_TO_USINT::dummyInit();
  FORTE_F_BYTE_TO_DINT::dummyInit();
  FORTE_F_BYTE_TO_DWORD::dummyInit();
  FORTE_F_BYTE_TO_INT::dummyInit();
  FORTE_F_BYTE_TO_LINT::dummyInit();
  FORTE_F_BYTE_TO_LWORD::dummyInit();
  FORTE_F_BYTE_TO_SINT::dummyInit();
  FORTE_F_BYTE_TO_STRING::dummyInit();
  FORTE_F_BYTE_TO_UDINT::dummyInit();
  FORTE_F_BYTE_TO_UINT::dummyInit();
  FORTE_F_BYTE_TO_ULINT::dummyInit();
  FORTE_F_BYTE_TO_USINT::dummyInit();
  FORTE_F_BYTE_TO_WORD::dummyInit();
  FORTE_F_BYTE_TO_WSTRING::dummyInit();
  FORTE_F_CONCAT::dummyInit();
  FORTE_F_CONCAT_DATE_TOD::dummyInit();
  FORTE_F_COS::dummyInit();
  FORTE_F_DELETE::dummyInit();
  FORTE_F_DINT_TO_BYTE::dummyInit();
  FORTE_F_DINT_TO_DWORD::dummyInit();
  FORTE_F_DINT_TO_INT::dummyInit();
  FORTE_F_DINT_TO_LINT::dummyInit();
  FORTE_F_DINT_TO_LREAL::dummyInit();
  FORTE_F_DINT_TO_LWORD::dummyInit();
  FORTE_F_DINT_TO_REAL::dummyInit();
  FORTE_F_DINT_TO_SINT::dummyInit();
  FORTE_F_DINT_TO_STRING::dummyInit();
  FORTE_F_DINT_TO_UDINT::dummyInit();
  FORTE_F_DINT_TO_UINT::dummyInit();
  FORTE_F_DINT_TO_ULINT::dummyInit();
  FORTE_F_DINT_TO_USINT::dummyInit();
  FORTE_F_DINT_TO_WORD::dummyInit();
  FORTE_F_DINT_TO_WSTRING::dummyInit();
  FORTE_F_DIV::dummyInit();
  FORTE_F_DIVTIME::dummyInit();
  FORTE_F_DT_TO_DATE::dummyInit();
  FORTE_F_DT_TO_TOD::dummyInit();
  FORTE_F_DWORD_BCD_TO_UDINT::dummyInit();
  FORTE_F_DWORD_TO_BYTE::dummyInit();
  FORTE_F_DWORD_TO_DINT::dummyInit();
  FORTE_F_DWORD_TO_INT::dummyInit();
  FORTE_F_DWORD_TO_LINT::dummyInit();
  FORTE_F_DWORD_TO_LWORD::dummyInit();
  FORTE_F_DWORD_TO_REAL::dummyInit();
  FORTE_F_DWORD_TO_SINT::dummyInit();
  FORTE_F_DWORD_TO_STRING::dummyInit();
  FORTE_F_DWORD_TO_UDINT::dummyInit();
  FORTE_F_DWORD_TO_UINT::dummyInit();
  FORTE_F_DWORD_TO_ULINT::dummyInit();
  FORTE_F_DWORD_TO_USINT::dummyInit();
  FORTE_F_DWORD_TO_WORD::dummyInit();
  FORTE_F_DWORD_TO_WSTRING::dummyInit();
  FORTE_F_EQ::dummyInit();
  FORTE_F_EXP::dummyInit();
  FORTE_F_EXPT::dummyInit();
  FORTE_F_FIND::dummyInit();
  FORTE_F_GE::dummyInit();
  FORTE_F_GT::dummyInit();
  FORTE_F_INSERT::dummyInit();
  FORTE_F_INT_TO_BYTE::dummyInit();
  FORTE_F_INT_TO_DINT::dummyInit();
  FORTE_F_INT_TO_DWORD::dummyInit();
  FORTE_F_INT_TO_LINT::dummyInit();
  FORTE_F_INT_TO_LREAL::dummyInit();
  FORTE_F_INT_TO_LWORD::dummyInit();
  FORTE_F_INT_TO_REAL::dummyInit();
  FORTE_F_INT_TO_SINT::dummyInit();
  FORTE_F_INT_TO_STRING::dummyInit();
  FORTE_F_INT_TO_UDINT::dummyInit();
  FORTE_F_INT_TO_UINT::dummyInit();
  FORTE_F_INT_TO_ULINT::dummyInit();
  FORTE_F_INT_TO_USINT::dummyInit();
  FORTE_F_INT_TO_WORD::dummyInit();
  FORTE_F_INT_TO_WSTRING::dummyInit();
  FORTE_F_LE::dummyInit();
  FORTE_F_LEFT::dummyInit();
  FORTE_F_LEN::dummyInit();
  FORTE_F_LIMIT::dummyInit();
  FORTE_F_LINT_TO_BYTE::dummyInit();
  FORTE_F_LINT_TO_DINT::dummyInit();
  FORTE_F_LINT_TO_DWORD::dummyInit();
  FORTE_F_LINT_TO_INT::dummyInit();
  FORTE_F_LINT_TO_LREAL::dummyInit();
  FORTE_F_LINT_TO_LWORD::dummyInit();
  FORTE_F_LINT_TO_REAL::dummyInit();
  FORTE_F_LINT_TO_SINT::dummyInit();
  FORTE_F_LINT_TO_STRING::dummyInit();
  FORTE_F_LINT_TO_UDINT::dummyInit();
  FORTE_F_LINT_TO_UINT::dummyInit();
  FORTE_F_LINT_TO_ULINT::dummyInit();
  FORTE_F_LINT_TO_USINT::dummyInit();
  FORTE_F_LINT_TO_WORD::dummyInit();
  FORTE_F_LINT_TO_WSTRING::dummyInit();
  FORTE_F_LN::dummyInit();
  FORTE_F_LOG::dummyInit();
  FORTE_F_LREAL_TO_DINT::dummyInit();
  FORTE_F_LREAL_TO_INT::dummyInit();
  FORTE_F_LREAL_TO_LINT::dummyInit();
  FORTE_F_LREAL_TO_LWORD::dummyInit();
  FORTE_F_LREAL_TO_REAL::dummyInit();
  FORTE_F_LREAL_TO_SINT::dummyInit();
  FORTE_F_LREAL_TO_STRING::dummyInit();
  FORTE_F_LREAL_TO_UDINT::dummyInit();
  FORTE_F_LREAL_TO_UINT::dummyInit();
  FORTE_F_LREAL_TO_ULINT::dummyInit();
  FORTE_F_LREAL_TO_USINT::dummyInit();
  FORTE_F_LREAL_TO_WSTRING::dummyInit();
  FORTE_F_LT::dummyInit();
  FORTE_F_LWORD_BCD_TO_ULINT::dummyInit();
  FORTE_F_LWORD_TO_BYTE::dummyInit();
  FORTE_F_LWORD_TO_DINT::dummyInit();
  FORTE_F_LWORD_TO_DWORD::dummyInit();
  FORTE_F_LWORD_TO_INT::dummyInit();
  FORTE_F_LWORD_TO_LINT::dummyInit();
  FORTE_F_LWORD_TO_LREAL::dummyInit();
  FORTE_F_LWORD_TO_SINT::dummyInit();
  FORTE_F_LWORD_TO_STRING::dummyInit();
  FORTE_F_LWORD_TO_UDINT::dummyInit();
  FORTE_F_LWORD_TO_UINT::dummyInit();
  FORTE_F_LWORD_TO_ULINT::dummyInit();
  FORTE_F_LWORD_TO_USINT::dummyInit();
  FORTE_F_LWORD_TO_WORD::dummyInit();
  FORTE_F_LWORD_TO_WSTRING::dummyInit();
  FORTE_F_MAX::dummyInit();
  FORTE_F_MID::dummyInit();
  FORTE_F_MIN::dummyInit();
  FORTE_F_MOD::dummyInit();
  FORTE_F_MOVE::dummyInit();
  FORTE_F_MUL::dummyInit();
  FORTE_F_MULTIME::dummyInit();
  FORTE_F_MUX_2::dummyInit();
  FORTE_F_NE::dummyInit();
  FORTE_F_NOT::dummyInit();
  FORTE_F_OR::dummyInit();
  FORTE_F_REAL_TO_DINT::dummyInit();
  FORTE_F_REAL_TO_DWORD::dummyInit();
  FORTE_F_REAL_TO_INT::dummyInit();
  FORTE_F_REAL_TO_LINT::dummyInit();
  FORTE_F_REAL_TO_LREAL::dummyInit();
  FORTE_F_REAL_TO_SINT::dummyInit();
  FORTE_F_REAL_TO_STRING::dummyInit();
  FORTE_F_REAL_TO_UDINT::dummyInit();
  FORTE_F_REAL_TO_UINT::dummyInit();
  FORTE_F_REAL_TO_ULINT::dummyInit();
  FORTE_F_REAL_TO_USINT::dummyInit();
  FORTE_F_REAL_TO_WSTRING::dummyInit();
  FORTE_F_REPLACE::dummyInit();
  FORTE_F_RIGHT::dummyInit();
  FORTE_F_ROL::dummyInit();
  FORTE_F_ROR::dummyInit();
  FORTE_F_SEL::dummyInit();
  FORTE_F_SHL::dummyInit();
  FORTE_F_SHR::dummyInit();
  FORTE_F_SIN::dummyInit();
  FORTE_F_SINT_TO_BYTE::dummyInit();
  FORTE_F_SINT_TO_DINT::dummyInit();
  FORTE_F_SINT_TO_DWORD::dummyInit();
  FORTE_F_SINT_TO_INT::dummyInit();
  FORTE_F_SINT_TO_LINT::dummyInit();
  FORTE_F_SINT_TO_LREAL::dummyInit();
  FORTE_F_SINT_TO_LWORD::dummyInit();
  FORTE_F_SINT_TO_REAL::dummyInit();
  FORTE_F_SINT_TO_STRING::dummyInit();
  FORTE_F_SINT_TO_UDINT::dummyInit();
  FORTE_F_SINT_TO_UINT::dummyInit();
  FORTE_F_SINT_TO_ULINT::dummyInit();
  FORTE_F_SINT_TO_USINT::dummyInit();
  FORTE_F_SINT_TO_WORD::dummyInit();
  FORTE_F_SINT_TO_WSTRING::dummyInit();
  FORTE_F_SQRT::dummyInit();
  FORTE_F_STRING_TO_BOOL::dummyInit();
  FORTE_F_STRING_TO_BYTE::dummyInit();
  FORTE_F_STRING_TO_DINT::dummyInit();
  FORTE_F_STRING_TO_DWORD::dummyInit();
  FORTE_F_STRING_TO_INT::dummyInit();
  FORTE_F_STRING_TO_LINT::dummyInit();
  FORTE_F_STRING_TO_LREAL::dummyInit();
  FORTE_F_STRING_TO_LWORD::dummyInit();
  FORTE_F_STRING_TO_REAL::dummyInit();
  FORTE_F_STRING_TO_SINT::dummyInit();
  FORTE_F_STRING_TO_TIME::dummyInit();
  FORTE_F_STRING_TO_UDINT::dummyInit();
  FORTE_F_STRING_TO_UINT::dummyInit();
  FORTE_F_STRING_TO_ULINT::dummyInit();
  FORTE_F_STRING_TO_USINT::dummyInit();
  FORTE_F_STRING_TO_WORD::dummyInit();
  FORTE_F_STRING_TO_WSTRING::dummyInit();
  FORTE_F_SUB::dummyInit();
  FORTE_F_SUB_DATE_DATE::dummyInit();
  FORTE_F_SUB_DT_DT::dummyInit();
  FORTE_F_SUB_DT_TIME::dummyInit();
  FORTE_F_SUB_TOD_TIME::dummyInit();
  FORTE_F_SUB_TOD_TOD::dummyInit();
  FORTE_F_TAN::dummyInit();
  FORTE_F_TIME_IN_MS_TO_LINT::dummyInit();
  FORTE_F_TIME_IN_MS_TO_LREAL::dummyInit();
  FORTE_F_TIME_IN_MS_TO_ULINT::dummyInit();
  FORTE_F_TIME_IN_NS_TO_LINT::dummyInit();
  FORTE_F_TIME_IN_NS_TO_LREAL::dummyInit();
  FORTE_F_TIME_IN_NS_TO_ULINT::dummyInit();
  FORTE_F_TIME_IN_S_TO_LINT::dummyInit();
  FORTE_F_TIME_IN_S_TO_LREAL::dummyInit();
  FORTE_F_TIME_IN_S_TO_ULINT::dummyInit();
  FORTE_F_TIME_IN_US_TO_LINT::dummyInit();
  FORTE_F_TIME_IN_US_TO_LREAL::dummyInit();
  FORTE_F_TIME_IN_US_TO_ULINT::dummyInit();
  FORTE_F_TIME_TO_STRING::dummyInit();
  FORTE_F_TIME_TO_WSTRING::dummyInit();
  FORTE_F_TRUNC::dummyInit();
  FORTE_F_UDINT_TO_BCD_DWORD::dummyInit();
  FORTE_F_UDINT_TO_BYTE::dummyInit();
  FORTE_F_UDINT_TO_DINT::dummyInit();
  FORTE_F_UDINT_TO_DWORD::dummyInit();
  FORTE_F_UDINT_TO_INT::dummyInit();
  FORTE_F_UDINT_TO_LINT::dummyInit();
  FORTE_F_UDINT_TO_LREAL::dummyInit();
  FORTE_F_UDINT_TO_LWORD::dummyInit();
  FORTE_F_UDINT_TO_REAL::dummyInit();
  FORTE_F_UDINT_TO_SINT::dummyInit();
  FORTE_F_UDINT_TO_STRING::dummyInit();
  FORTE_F_UDINT_TO_UINT::dummyInit();
  FORTE_F_UDINT_TO_ULINT::dummyInit();
  FORTE_F_UDINT_TO_WORD::dummyInit();
  FORTE_F_UDINT_TO_WSTRING::dummyInit();
  FORTE_F_UINT_TO_BCD_WORD::dummyInit();
  FORTE_F_UINT_TO_BYTE::dummyInit();
  FORTE_F_UINT_TO_DINT::dummyInit();
  FORTE_F_UINT_TO_DWORD::dummyInit();
  FORTE_F_UINT_TO_INT::dummyInit();
  FORTE_F_UINT_TO_LINT::dummyInit();
  FORTE_F_UINT_TO_LREAL::dummyInit();
  FORTE_F_UINT_TO_LWORD::dummyInit();
  FORTE_F_UINT_TO_REAL::dummyInit();
  FORTE_F_UINT_TO_SINT::dummyInit();
  FORTE_F_UINT_TO_STRING::dummyInit();
  FORTE_F_UINT_TO_UDINT::dummyInit();
  FORTE_F_UINT_TO_ULINT::dummyInit();
  FORTE_F_UINT_TO_USINT::dummyInit();
  FORTE_F_UINT_TO_WORD::dummyInit();
  FORTE_F_UINT_TO_WSTRING::dummyInit();
  FORTE_F_ULINT_TO_BCD_LWORD::dummyInit();
  FORTE_F_ULINT_TO_BYTE::dummyInit();
  FORTE_F_ULINT_TO_DINT::dummyInit();
  FORTE_F_ULINT_TO_DWORD::dummyInit();
  FORTE_F_ULINT_TO_INT::dummyInit();
  FORTE_F_ULINT_TO_LINT::dummyInit();
  FORTE_F_ULINT_TO_LREAL::dummyInit();
  FORTE_F_ULINT_TO_LWORD::dummyInit();
  FORTE_F_ULINT_TO_REAL::dummyInit();
  FORTE_F_ULINT_TO_SINT::dummyInit();
  FORTE_F_ULINT_TO_STRING::dummyInit();
  FORTE_F_ULINT_TO_UDINT::dummyInit();
  FORTE_F_ULINT_TO_UINT::dummyInit();
  FORTE_F_ULINT_TO_USINT::dummyInit();
  FORTE_F_ULINT_TO_WORD::dummyInit();
  FORTE_F_ULINT_TO_WSTRING::dummyInit();
  FORTE_F_USINT_TO_BCD_BYTE::dummyInit();
  FORTE_F_USINT_TO_BYTE::dummyInit();
  FORTE_F_USINT_TO_DINT::dummyInit();
  FORTE_F_USINT_TO_DWORD::dummyInit();
  FORTE_F_USINT_TO_INT::dummyInit();
  FORTE_F_USINT_TO_LINT::dummyInit();
  FORTE_F_USINT_TO_LREAL::dummyInit();
  FORTE_F_USINT_TO_LWORD::dummyInit();
  FORTE_F_USINT_TO_REAL::dummyInit();
  FORTE_F_USINT_TO_SINT::dummyInit();
  FORTE_F_USINT_TO_STRING::dummyInit();
  FORTE_F_USINT_TO_UDINT::dummyInit();
  FORTE_F_USINT_TO_UINT::dummyInit();
  FORTE_F_USINT_TO_ULINT::dummyInit();
  FORTE_F_USINT_TO_WORD::dummyInit();
  FORTE_F_USINT_TO_WSTRING::dummyInit();
  FORTE_F_WORD_BCD_TO_UINT::dummyInit();
  FORTE_F_WORD_TO_BYTE::dummyInit();
  FORTE_F_WORD_TO_DINT::dummyInit();
  FORTE_F_WORD_TO_DWORD::dummyInit();
  FORTE_F_WORD_TO_INT::dummyInit();
  FORTE_F_WORD_TO_LINT::dummyInit();
  FORTE_F_WORD_TO_LWORD::dummyInit();
  FORTE_F_WORD_TO_SINT::dummyInit();
  FORTE_F_WORD_TO_STRING::dummyInit();
  FORTE_F_WORD_TO_UDINT::dummyInit();
  FORTE_F_WORD_TO_UINT::dummyInit();
  FORTE_F_WORD_TO_ULINT::dummyInit();
  FORTE_F_WORD_TO_USINT::dummyInit();
  FORTE_F_WORD_TO_WSTRING::dummyInit();
  FORTE_F_WSTRING_TO_BOOL::dummyInit();
  FORTE_F_WSTRING_TO_BYTE::dummyInit();
  FORTE_F_WSTRING_TO_DINT::dummyInit();
  FORTE_F_WSTRING_TO_DWORD::dummyInit();
  FORTE_F_WSTRING_TO_INT::dummyInit();
  FORTE_F_WSTRING_TO_LINT::dummyInit();
  FORTE_F_WSTRING_TO_LREAL::dummyInit();
  FORTE_F_WSTRING_TO_LWORD::dummyInit();
  FORTE_F_WSTRING_TO_REAL::dummyInit();
  FORTE_F_WSTRING_TO_SINT::dummyInit();
  FORTE_F_WSTRING_TO_STRING::dummyInit();
  FORTE_F_WSTRING_TO_TIME::dummyInit();
  FORTE_F_WSTRING_TO_UDINT::dummyInit();
  FORTE_F_WSTRING_TO_UINT::dummyInit();
  FORTE_F_WSTRING_TO_ULINT::dummyInit();
  FORTE_F_WSTRING_TO_USINT::dummyInit();
  FORTE_F_WSTRING_TO_WORD::dummyInit();
  FORTE_F_XOR::dummyInit();
  FORTE_GET_AT_INDEX::dummyInit();
  FORTE_GET_STRUCT_VALUE::dummyInit();
  FORTE_OUT_ANY_CONSOLE::dummyInit();
  FORTE_SET_AT_INDEX::dummyInit();
  FORTE_STEST_END::dummyInit();
  FORTE_ST_CREATE_CONN::dummyInit();
  FORTE_ST_CREATE_FB::dummyInit();
  FORTE_ST_DEL_CONN::dummyInit();
  FORTE_ST_DEL_FB::dummyInit();
  FORTE_ST_REC_CONN::dummyInit();
  FORTE_ST_SET_PARM::dummyInit();
  FORTE_TEST_CONDITION::dummyInit();
  FORTE_Vibrator::dummyInit();
  GEN_ADD::dummyInit();
  GEN_AND::dummyInit();
  GEN_APPEND_STRING::dummyInit();
  GEN_ARRAY2ARRAY::dummyInit();
  GEN_ARRAY2VALUES::dummyInit();
  GEN_CLIENT::dummyInit();
  GEN_CSV_WRITER::dummyInit();
  GEN_E_DEMUX::dummyInit();
  GEN_E_MUX::dummyInit();
  GEN_F_MUX::dummyInit();
  GEN_OR::dummyInit();
  GEN_PUBL::dummyInit();
  GEN_PUBLISH::dummyInit();
  GEN_SERVER::dummyInit();
  GEN_STRUCT_DEMUX::dummyInit();
  GEN_STRUCT_MUX::dummyInit();
  GEN_SUBL::dummyInit();
  GEN_SUBSCRIBE::dummyInit();
  GEN_VALUES2ARRAY::dummyInit();
  GEN_XOR::dummyInit();
  INT2INT::dummyInit();
  LREAL2LREAL::dummyInit();
  REAL2REAL::dummyInit();
  RMT_RES::dummyInit();
  SINT2SINT::dummyInit();
  STRING2STRING::dummyInit();
  TIME2TIME::dummyInit();
  UDINT2UDINT::dummyInit();
  UINT2UINT::dummyInit();
  USINT2USINT::dummyInit();
  WORD2WORD::dummyInit();
  WSTRING2WSTRING::dummyInit();


}


