/*******************************************************************************
 * Copyright (c) 2012 Profactor GmbH
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Michael Hofmann
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
 extern const CStringDictionary::TStringId g_nStringIdBUNKER_FEED_CAPS;
 extern const CStringDictionary::TStringId g_nStringIdCAP_NOT_REACHANBLE;
 extern const CStringDictionary::TStringId g_nStringIdCAP_RECHANBLE;
 extern const CStringDictionary::TStringId g_nStringIdCAP_REQUIRED;
 extern const CStringDictionary::TStringId g_nStringIdCamera;
 extern const CStringDictionary::TStringId g_nStringIdDESIRED_COLOR_CAP_NOT_AVAILABLE;
 extern const CStringDictionary::TStringId g_nStringIdPick_Pos_X;
 extern const CStringDictionary::TStringId g_nStringIdPick_Pos_Y;
 extern const CStringDictionary::TStringId g_nStringIdPick_Pos_Z;
 extern const CStringDictionary::TStringId g_nStringIdProduct_Color;
 extern const CStringDictionary::TStringId g_nStringIdSINT;
 extern const CStringDictionary::TStringId g_nStringIdSTRING;
 extern const CStringDictionary::TStringId g_nStringIdVIBRATOR_CAP_REACHABLE;
 extern const CStringDictionary::TStringId g_nStringIdVIBRATOR_ORIENTED_CORRECT;
 extern const CStringDictionary::TStringId g_nStringIdWRONG_CAP_ORIENTATION;

