/*******************************************************************************
 * Copyright (c) 2012 Profactor GmbH
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Michael Hofmann
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
 extern const CStringDictionary::TStringId g_nStringIdBOOL;
 extern const CStringDictionary::TStringId g_nStringIdCNF;
 extern const CStringDictionary::TStringId g_nStringIdContentFilter;
 extern const CStringDictionary::TStringId g_nStringIdEI;
 extern const CStringDictionary::TStringId g_nStringIdEO1;
 extern const CStringDictionary::TStringId g_nStringIdE_SWITCH;
 extern const CStringDictionary::TStringId g_nStringIdE_SWITCH_1;
 extern const CStringDictionary::TStringId g_nStringIdError;
 extern const CStringDictionary::TStringId g_nStringIdF_EQ;
 extern const CStringDictionary::TStringId g_nStringIdFilter_name;
 extern const CStringDictionary::TStringId g_nStringIdG;
 extern const CStringDictionary::TStringId g_nStringIdGET_STRUCT_VALUE;
 extern const CStringDictionary::TStringId g_nStringIdGET_STRUCT_VALUE_2;
 extern const CStringDictionary::TStringId g_nStringIdGET_STRUCT_VALUE_3;
 extern const CStringDictionary::TStringId g_nStringIdIN;
 extern const CStringDictionary::TStringId g_nStringIdIN1;
 extern const CStringDictionary::TStringId g_nStringIdIN2;
 extern const CStringDictionary::TStringId g_nStringIdNew_Value;
 extern const CStringDictionary::TStringId g_nStringIdOUT;
 extern const CStringDictionary::TStringId g_nStringIdREQ;
 extern const CStringDictionary::TStringId g_nStringIdSTRING;
 extern const CStringDictionary::TStringId g_nStringIdSTRING2STRING;
 extern const CStringDictionary::TStringId g_nStringIdStruct_Message;
 extern const CStringDictionary::TStringId g_nStringIdUSINT2USINT;
 extern const CStringDictionary::TStringId g_nStringIdin_struct;
 extern const CStringDictionary::TStringId g_nStringIdmember;
 extern const CStringDictionary::TStringId g_nStringIdoutput;
 extern const CStringDictionary::TStringId g_nStringIdspinner;

