/*******************************************************************************
 * Copyright (c) 2012 Profactor GmbH
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Michael Hofmann
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
 extern const CStringDictionary::TStringId g_nStringIdCTR;
 extern const CStringDictionary::TStringId g_nStringIdCU;
 extern const CStringDictionary::TStringId g_nStringIdCUO;
 extern const CStringDictionary::TStringId g_nStringIdCV;
 extern const CStringDictionary::TStringId g_nStringIdDLY;
 extern const CStringDictionary::TStringId g_nStringIdDT;
 extern const CStringDictionary::TStringId g_nStringIdEI;
 extern const CStringDictionary::TStringId g_nStringIdEO;
 extern const CStringDictionary::TStringId g_nStringIdEO0;
 extern const CStringDictionary::TStringId g_nStringIdE_CTU;
 extern const CStringDictionary::TStringId g_nStringIdE_DELAY;
 extern const CStringDictionary::TStringId g_nStringIdE_SWITCH;
 extern const CStringDictionary::TStringId g_nStringIdE_TRAIN;
 extern const CStringDictionary::TStringId g_nStringIdG;
 extern const CStringDictionary::TStringId g_nStringIdGATE;
 extern const CStringDictionary::TStringId g_nStringIdN;
 extern const CStringDictionary::TStringId g_nStringIdPV;
 extern const CStringDictionary::TStringId g_nStringIdQ;
 extern const CStringDictionary::TStringId g_nStringIdR;
 extern const CStringDictionary::TStringId g_nStringIdRO;
 extern const CStringDictionary::TStringId g_nStringIdSTART;
 extern const CStringDictionary::TStringId g_nStringIdSTOP;
 extern const CStringDictionary::TStringId g_nStringIdTIME;
 extern const CStringDictionary::TStringId g_nStringIdUINT;

