/*******************************************************************************
 * Copyright (c) 2012 Profactor GmbH
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Michael Hofmann
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
 extern const CStringDictionary::TStringId g_nStringIdBOOL;
 extern const CStringDictionary::TStringId g_nStringIdCD;
 extern const CStringDictionary::TStringId g_nStringIdCNF;
 extern const CStringDictionary::TStringId g_nStringIdCU;
 extern const CStringDictionary::TStringId g_nStringIdCV;
 extern const CStringDictionary::TStringId g_nStringIdDINT;
 extern const CStringDictionary::TStringId g_nStringIdFB_CTUD_DINT;
 extern const CStringDictionary::TStringId g_nStringIdLD;
 extern const CStringDictionary::TStringId g_nStringIdPV;
 extern const CStringDictionary::TStringId g_nStringIdQD;
 extern const CStringDictionary::TStringId g_nStringIdQU;
 extern const CStringDictionary::TStringId g_nStringIdR;
 extern const CStringDictionary::TStringId g_nStringIdREQ;

