/*******************************************************************************
 * Copyright (c) 2012 Profactor GmbH
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Michael Hofmann
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
 extern const CStringDictionary::TStringId g_nStringIdANY;
 extern const CStringDictionary::TStringId g_nStringIdBOOL;
 extern const CStringDictionary::TStringId g_nStringIdBYTE;
 extern const CStringDictionary::TStringId g_nStringIdDATE;
 extern const CStringDictionary::TStringId g_nStringIdDATE_AND_TIME;
 extern const CStringDictionary::TStringId g_nStringIdDINT;
 extern const CStringDictionary::TStringId g_nStringIdDWORD;
 extern const CStringDictionary::TStringId g_nStringIdINT;
 extern const CStringDictionary::TStringId g_nStringIdLINT;
 extern const CStringDictionary::TStringId g_nStringIdLREAL;
 extern const CStringDictionary::TStringId g_nStringIdLWORD;
 extern const CStringDictionary::TStringId g_nStringIdREAL;
 extern const CStringDictionary::TStringId g_nStringIdSINT;
 extern const CStringDictionary::TStringId g_nStringIdSTRING;
 extern const CStringDictionary::TStringId g_nStringIdTIME;
 extern const CStringDictionary::TStringId g_nStringIdTIME_OF_DAY;
 extern const CStringDictionary::TStringId g_nStringIdUDINT;
 extern const CStringDictionary::TStringId g_nStringIdUINT;
 extern const CStringDictionary::TStringId g_nStringIdULINT;
 extern const CStringDictionary::TStringId g_nStringIdUSINT;
 extern const CStringDictionary::TStringId g_nStringIdWORD;
 extern const CStringDictionary::TStringId g_nStringIdWSTRING;

