/*******************************************************************************
 * Copyright (c) 2012 Profactor GmbH
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Michael Hofmann
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
 extern const CStringDictionary::TStringId g_nStringIdANY;
 extern const CStringDictionary::TStringId g_nStringIdBOOL;
 extern const CStringDictionary::TStringId g_nStringIdCNF;
 extern const CStringDictionary::TStringId g_nStringIdGET_STRUCT_VALUE;
 extern const CStringDictionary::TStringId g_nStringIdQO;
 extern const CStringDictionary::TStringId g_nStringIdREQ;
 extern const CStringDictionary::TStringId g_nStringIdSTRING;
 extern const CStringDictionary::TStringId g_nStringIdin_struct;
 extern const CStringDictionary::TStringId g_nStringIdmember;
 extern const CStringDictionary::TStringId g_nStringIdoutput;

