/*******************************************************************************
 * Copyright (c) 2012 Profactor GmbH
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Michael Hofmann
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
 extern const CStringDictionary::TStringId g_nStringIdCOLD;
 extern const CStringDictionary::TStringId g_nStringIdDEV_MGR;
 extern const CStringDictionary::TStringId g_nStringIdEO;
 extern const CStringDictionary::TStringId g_nStringIdE_RESTART;
 extern const CStringDictionary::TStringId g_nStringIdE_SR;
 extern const CStringDictionary::TStringId g_nStringIdID;
 extern const CStringDictionary::TStringId g_nStringIdINIT;
 extern const CStringDictionary::TStringId g_nStringIdMGR;
 extern const CStringDictionary::TStringId g_nStringIdMGR_FF;
 extern const CStringDictionary::TStringId g_nStringIdMGR_ID;
 extern const CStringDictionary::TStringId g_nStringIdQ;
 extern const CStringDictionary::TStringId g_nStringIdQI;
 extern const CStringDictionary::TStringId g_nStringIdR;
 extern const CStringDictionary::TStringId g_nStringIdRMT_RES;
 extern const CStringDictionary::TStringId g_nStringIdS;
 extern const CStringDictionary::TStringId g_nStringIdSTART;
 extern const CStringDictionary::TStringId g_nStringIdSTOP;
 extern const CStringDictionary::TStringId g_nStringIdWSTRING;
 extern const CStringDictionary::TStringId g_nStringIdwARM;

