/*******************************************************************************
 * Copyright (c) 2012 Profactor GmbH
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Michael Hofmann
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
 extern const CStringDictionary::TStringId g_nStringIdANY;
 extern const CStringDictionary::TStringId g_nStringIdBOOL;
 extern const CStringDictionary::TStringId g_nStringIdCNF;
 extern const CStringDictionary::TStringId g_nStringIdINDEX;
 extern const CStringDictionary::TStringId g_nStringIdIN_ARRAY;
 extern const CStringDictionary::TStringId g_nStringIdOUT_ARRAY;
 extern const CStringDictionary::TStringId g_nStringIdQO;
 extern const CStringDictionary::TStringId g_nStringIdREQ;
 extern const CStringDictionary::TStringId g_nStringIdSET_AT_INDEX;
 extern const CStringDictionary::TStringId g_nStringIdUINT;
 extern const CStringDictionary::TStringId g_nStringIdVALUE;

